%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters.
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 396.70760099999995
Camera.fy: 469.5846480794702
Camera.cx: 323.5571166666666
Camera.cy: 238.71953562913907

Camera.k1: -0.089289
Camera.k2: 0.001958
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0

Camera.width: 640
Camera.height: 480

# Camera frames per second
Camera.fps: 24

# IR projector baseline times fx (aprox.)
# Camera.bf: 387.5744
Camera.bf: 396.70760099999995

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# System Parameters
#--------------------------------------------------------------------------------------------

# Switch for Dataset (1 for Oxford MultiMotion Dataset, 2 for KITTI dataset, 3...)
ChooseData: 2

# Deptmap values factor
DepthMapFactor: 280

# Close/Far Depth threshold
#ThDepthBG: 40.0
ThDepthBG: 60
ThDepthOBJ: 45

# Max Tracking Points on Background and Object in each frame
MaxTrackPointBG: 1500 # 1200
MaxTrackPointOBJ: 800 # 800

# Scene Flow Magnitude and Distribution Threshold
SFMgThres: 0.05 # 0.05 #0.12
SFDsThres: 0.99 # 0.99 #0.3

# Window Size and Overlapping Size for Local Batch Optimization
WINDOW_SIZE: 20
OVERLAP_SIZE: 4

# Use sampled feature or detected feature for background (1: sampled, 0: detected)
UseSampleFeature: 1

#--------------------------------------------------------------------------------------------
# ORB Parameters (NOTE: only FAST corners are used in this system.)
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2500

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7




